version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "18:00"
      timezone: America/Chicago
    open-pull-requests-limit: 99
    reviewers:
      - Workiva/xt
    ignore:
      - dependency-name: numpy
        versions:
          - ">=1.20"
      - dependency-name: pyparsing
        versions:
          - ">=3.0.0"
